// 04__ai/ai-notes/apps/web/src/components/Navbar.svelte
<script lang="ts">
	interface User {
		name: string;
		email: string;
		createdAt?: string | Date;
	}

	interface Props {
		user: User | null | undefined;
		loggingOut?: boolean;
		onlogout?: () => void;
	}

	let { user, loggingOut = false, onlogout }: Props = $props();
</script>

<nav
	class="sticky top-0 z-50 border-b border-slate-900/80 bg-slate-950/40 px-6 py-4 backdrop-blur-xl"
>
	<div class="mx-auto flex max-w-6xl items-center justify-between">
		<!-- Logo -->
		<a href={user ? '/dashboard' : '/'} class="group flex items-center gap-2.5">
			<span
				class="bg-linear-to-r from-violet-400 via-indigo-400 to-fuchsia-400 bg-clip-text text-xl font-bold tracking-tight text-transparent text-white transition duration-300 group-hover:from-violet-300 group-hover:via-indigo-300 group-hover:to-fuchsia-300"
			>
				AI Notes
			</span>
		</a>

		<!-- Auth Actions / Nav Links -->
		<div class="flex items-center gap-6">
			{#if user}
				<a
					href="/dashboard"
					class="text-sm font-medium text-slate-400 transition-colors duration-200 hover:text-white"
				>
					Dashboard
				</a>
				<div class="h-4 w-px bg-slate-800/80"></div>
				<div class="flex items-center gap-3">
					<div
						class="flex h-8 w-8 items-center justify-center rounded-full bg-linear-to-tr from-violet-500 to-indigo-500 p-[1px]"
					>
						<div
							class="flex h-full w-full items-center justify-center rounded-full bg-slate-950 text-xs font-bold text-violet-300"
						>
							{user.name.charAt(0).toUpperCase()}
						</div>
					</div>
					<span class="hidden text-sm font-medium text-slate-300 sm:inline">
						{user.name}
					</span>
					<button
						onclick={onlogout}
						disabled={loggingOut}
						class="cursor-pointer rounded-lg border border-slate-800/80 bg-slate-900/60 px-3 py-1.5 text-xs font-semibold text-slate-400 transition duration-200 hover:bg-slate-900 hover:text-white disabled:opacity-50"
					>
						{#if loggingOut}
							Sign out...
						{:else}
							Logout
						{/if}
					</button>
				</div>
			{:else}
				<a
					href="/login"
					class="text-sm font-medium text-slate-400 transition-colors duration-200 hover:text-white"
				>
					Sign In
				</a>
				<a
					href="/register"
					class="rounded-xl border border-violet-500/20 bg-gradient-to-r from-violet-600 to-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-lg shadow-violet-950/20 transition-all duration-300 hover:border-violet-400/40 hover:from-violet-500 hover:to-indigo-500 active:scale-[0.98]"
				>
					Register
				</a>
			{/if}
		</div>
	</div>
</nav>

// 06__full-stack/dispatcher/frontend/src/components/Navbar.tsx
import React from 'react';
import { useAuth } from '../features/auth/context/AuthContext';
import { Truck, LayoutDashboard, Route, History, User as UserIcon, LogOut, LogIn, UserPlus } from 'lucide-react';

interface NavbarProps {
  currentView: string;
  onNavigate: (view: string) => void;
}

export const Navbar: React.FC<NavbarProps> = ({ currentView, onNavigate }) => {
  const { user, isAuthenticated, logout } = useAuth();

  return (
    <header className="border-b border-neutral-200 bg-neutral-50/90 backdrop-blur-md sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
        {/* Brand Logo */}
        <button
          onClick={() => onNavigate('dashboard')}
          className="flex items-center gap-3 bg-transparent border-0 cursor-pointer text-left"
        >
          <div className="p-2 bg-brand-600 rounded-xl shadow-lg shadow-brand-600/30 text-neutral-0">
            <Truck className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-lg font-bold text-neutral-900 tracking-tight leading-tight">
              Trip Planner
            </h1>
            <p className="text-[11px] text-brand-600 font-medium">HOS & ELD Dispatcher</p>
          </div>
        </button>

        {/* Navigation Links */}
        <nav className="hidden md:flex items-center gap-1">
          <button
            onClick={() => onNavigate('dashboard')}
            className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-sm font-medium transition-all cursor-pointer ${
              currentView === 'dashboard'
                ? 'bg-brand-50 text-brand-600 border border-brand-300'
                : 'text-neutral-600 hover:text-neutral-900 hover:bg-neutral-100'
            }`}
          >
            <LayoutDashboard className="w-4 h-4" />
            Dashboard
          </button>

          <button
            onClick={() => onNavigate('route-planner')}
            className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-sm font-medium transition-all cursor-pointer ${
              currentView === 'route-planner'
                ? 'bg-brand-50 text-brand-600 border border-brand-300'
                : 'text-neutral-600 hover:text-neutral-900 hover:bg-neutral-100'
            }`}
          >
            <Route className="w-4 h-4" />
            New Trip
          </button>

          <button
            onClick={() => onNavigate('trip-history')}
            className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-sm font-medium transition-all cursor-pointer ${
              currentView === 'trip-history'
                ? 'bg-brand-50 text-brand-600 border border-brand-300'
                : 'text-neutral-600 hover:text-neutral-900 hover:bg-neutral-100'
            }`}
          >
            <History className="w-4 h-4" />
            Trip History
          </button>
        </nav>

        {/* User / Auth Controls */}
        <div className="flex items-center gap-3">
          {isAuthenticated ? (
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-neutral-100 border border-neutral-200">
                <UserIcon className="w-4 h-4 text-brand-600" />
                <span className="text-xs font-semibold text-neutral-800">
                  {user?.first_name || user?.email.split('@')[0]}
                </span>
              </div>
              <button
                onClick={logout}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-neutral-100 hover:bg-error-50 text-neutral-600 hover:text-error-600 border border-neutral-200 hover:border-error-300 text-xs font-medium transition-all cursor-pointer"
              >
                <LogOut className="w-3.5 h-3.5" />
                Logout
              </button>
            </div>
          ) : (
            <div className="flex items-center gap-2">
              <button
                onClick={() => onNavigate('login')}
                className={`flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-xs font-medium transition-all cursor-pointer border ${
                  currentView === 'login'
                    ? 'bg-brand-600 text-neutral-0 border-brand-500'
                    : 'bg-neutral-100 text-neutral-800 border-neutral-200 hover:bg-neutral-200'
                }`}
              >
                <LogIn className="w-3.5 h-3.5" />
                Sign In
              </button>
              <button
                onClick={() => onNavigate('register')}
                className={`flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-xs font-medium transition-all cursor-pointer border ${
                  currentView === 'register'
                    ? 'bg-brand-600 text-neutral-0 border-brand-500'
                    : 'bg-brand-50 text-brand-600 border-brand-300 hover:bg-brand-100'
                }`}
              >
                <UserPlus className="w-3.5 h-3.5" />
                Register
              </button>
            </div>
          )}
        </div>
      </div>
    </header>
  );
};
