// 06__full-stack/barbhq/dashboard/src/components/ui/button.tsx
import React from "react";
import { cn } from "../../lib/utils";
import { Loader2 } from "lucide-react";

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?:
    | "primary"
    | "secondary"
    | "outline"
    | "ghost"
    | "destructive"
    | "default"
    | "link";
  size?: "sm" | "md" | "lg" | "default" | "icon" | "icon-sm" | "icon-xs";
  isLoading?: boolean;
  render?: React.ReactNode;
}

export const buttonVariants = (options?: {
  variant?: string;
  size?: string;
  className?: string;
}) => {
  const variant = options?.variant || "primary";
  const size = options?.size || "md";
  const className = options?.className || "";

  return cn(
    "inline-flex items-center justify-center rounded-lg font-medium transition-all duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 active:scale-95 disabled:pointer-events-none disabled:opacity-50 cursor-pointer",
    {
      "bg-primary text-primary-foreground hover:bg-primary/90 shadow-md shadow-primary/10 hover:shadow-lg hover:shadow-primary/20":
        variant === "primary" || variant === "default",
      "bg-secondary text-secondary-foreground hover:bg-secondary/80":
        variant === "secondary",
      "border border-border bg-transparent text-foreground hover:bg-secondary/60":
        variant === "outline",
      "bg-transparent text-foreground hover:bg-secondary/85":
        variant === "ghost",
      "bg-destructive text-destructive-foreground hover:bg-destructive/90 shadow-md shadow-destructive/10":
        variant === "destructive",
      "bg-transparent text-primary underline-offset-4 hover:underline active:scale-100":
        variant === "link",
    },
    {
      "px-3 py-1.5 text-xs gap-1.5": size === "sm",
      "px-4 py-2.5 text-sm gap-2": size === "md" || size === "default",
      "px-6 py-3.5 text-base gap-2.5": size === "lg",
      "h-9 w-9 p-0 justify-center shrink-0": size === "icon",
      "h-8 w-8 p-0 justify-center shrink-0 text-xs": size === "icon-sm",
      "h-7 w-7 p-0 justify-center shrink-0 text-[10px]": size === "icon-xs",
    },
    className,
  );
};

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      className,
      variant = "primary",
      size = "md",
      isLoading,
      disabled,
      render,
      children,
      ...props
    },
    ref,
  ) => {
    // Support custom inline element rendering (radix-slot pattern)
    if (render && React.isValidElement(render)) {
      const renderElement = render as React.ReactElement<{
        className?: string;
        ref?: React.Ref<HTMLElement>;
        disabled?: boolean;
      }>;
      return React.cloneElement(renderElement, {
        ref,
        className: cn(
          buttonVariants({ variant, size, className }),
          renderElement.props.className,
        ),
        disabled: disabled || isLoading,
        ...props,
      });
    }

    return (
      <button
        ref={ref}
        disabled={disabled || isLoading}
        className={buttonVariants({ variant, size, className })}
        {...props}
      >
        {isLoading ? (
          <Loader2 className="h-4 w-4 animate-spin text-current" />
        ) : null}
        {children}
      </button>
    );
  },
);

Button.displayName = "Button";

// 06__full-stack/serverpilot/apps/web/src/lib/components/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import Spinner from './Spinner.svelte';

	let {
		children,
		variant = 'default',
		size = 'md',
		type = 'button',
		disabled = false,
		loading = false,
		onclick,
		class: className = '',
		...rest
	} = $props<{
		children: Snippet;
		variant?: 'default' | 'secondary' | 'outline' | 'ghost' | 'destructive';
		size?: 'sm' | 'md' | 'lg';
		type?: 'button' | 'submit' | 'reset';
		disabled?: boolean;
		loading?: boolean;
		onclick?: (e: MouseEvent) => void;
		class?: string;
		[key: string]: any;
	}>();

	const variantClasses = {
		default:
			'bg-indigo-600 text-white hover:bg-indigo-500 shadow-lg shadow-indigo-500/10 focus-visible:ring-indigo-500 active:scale-[0.98]',
		secondary:
			'bg-zinc-800 text-zinc-150 hover:bg-zinc-700 border border-zinc-700/60 focus-visible:ring-zinc-700 active:scale-[0.98]',
		outline:
			'bg-transparent text-zinc-300 border border-zinc-700 hover:bg-zinc-900/50 hover:text-zinc-100 focus-visible:ring-zinc-700 active:scale-[0.98]',
		ghost:
			'bg-transparent text-zinc-400 hover:bg-zinc-900/50 hover:text-zinc-200 focus-visible:ring-zinc-800',
		destructive:
			'bg-red-950/40 text-red-200 border border-red-900/50 hover:bg-red-900/40 hover:text-red-100 focus-visible:ring-red-700 active:scale-[0.98]'
	};

	const sizeClasses = {
		sm: 'h-9 px-3 text-xs rounded-md',
		md: 'h-10 px-4 py-2 text-sm rounded-lg',
		lg: 'h-11 px-8 text-base rounded-xl'
	};
</script>

<button
	{type}
	disabled={disabled || loading}
	{onclick}
	class="inline-flex cursor-pointer items-center justify-center gap-2 font-semibold transition-all select-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-zinc-950 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 {variantClasses[
		variant
	]} {sizeClasses[size]} {className}"
	{...rest}
>
	{#if loading}
		<Spinner size="sm" color={variant === 'default' ? 'white' : 'indigo'} />
	{/if}
	{@render children()}
</button>
