// 06__full-stack/serverpilot/apps/web/src/lib/components/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import Spinner from './Spinner.svelte';

	let {
		children,
		variant = 'default',
		size = 'md',
		type = 'button',
		disabled = false,
		loading = false,
		onclick,
		class: className = '',
		...rest
	} = $props<{
		children: Snippet;
		variant?: 'default' | 'secondary' | 'outline' | 'ghost' | 'destructive';
		size?: 'sm' | 'md' | 'lg';
		type?: 'button' | 'submit' | 'reset';
		disabled?: boolean;
		loading?: boolean;
		onclick?: (e: MouseEvent) => void;
		class?: string;
		[key: string]: any;
	}>();

	const variantClasses = {
		default:
			'bg-indigo-600 text-white hover:bg-indigo-500 shadow-lg shadow-indigo-500/10 focus-visible:ring-indigo-500 active:scale-[0.98]',
		secondary:
			'bg-zinc-800 text-zinc-150 hover:bg-zinc-700 border border-zinc-700/60 focus-visible:ring-zinc-700 active:scale-[0.98]',
		outline:
			'bg-transparent text-zinc-300 border border-zinc-700 hover:bg-zinc-900/50 hover:text-zinc-100 focus-visible:ring-zinc-700 active:scale-[0.98]',
		ghost:
			'bg-transparent text-zinc-400 hover:bg-zinc-900/50 hover:text-zinc-200 focus-visible:ring-zinc-800',
		destructive:
			'bg-red-950/40 text-red-200 border border-red-900/50 hover:bg-red-900/40 hover:text-red-100 focus-visible:ring-red-700 active:scale-[0.98]'
	};

	const sizeClasses = {
		sm: 'h-9 px-3 text-xs rounded-md',
		md: 'h-10 px-4 py-2 text-sm rounded-lg',
		lg: 'h-11 px-8 text-base rounded-xl'
	};
</script>

<button
	{type}
	disabled={disabled || loading}
	{onclick}
	class="inline-flex cursor-pointer items-center justify-center gap-2 font-semibold transition-all select-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-zinc-950 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 {variantClasses[
		variant
	]} {sizeClasses[size]} {className}"
	{...rest}
>
	{#if loading}
		<Spinner size="sm" color={variant === 'default' ? 'white' : 'indigo'} />
	{/if}
	{@render children()}
</button>

// 06__full-stack/nimbusdrive/apps/web/src/lib/component/ui/Button.jsx
import React from "react";
import { cn } from "../../utils";

export const Button = React.forwardRef(({
  className,
  variant = "default",
  size = "default",
  ...props
}, ref) => {
  const baseStyles = 
    "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-xl text-sm font-medium transition-all duration-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-purple-500 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0";
  
  const variants = {
    default: "bg-gradient-to-r from-purple-600 to-indigo-600 text-white shadow-lg shadow-purple-500/20 hover:from-purple-500 hover:to-indigo-500 hover:shadow-purple-500/30",
    destructive: "bg-rose-600 text-white shadow-sm hover:bg-rose-500",
    outline: "border border-slate-800 bg-transparent text-slate-300 hover:bg-slate-900 hover:text-white",
    secondary: "bg-slate-800 text-slate-100 hover:bg-slate-700",
    ghost: "text-slate-400 hover:bg-slate-900 hover:text-white",
    link: "text-purple-400 underline-offset-4 hover:underline"
  };

  const sizes = {
    default: "h-10 px-4 py-2",
    sm: "h-9 rounded-lg px-3 text-xs",
    lg: "h-11 rounded-xl px-8",
    icon: "h-10 w-10"
  };

  return (
    <button
      className={cn(baseStyles, variants[variant], sizes[size], className)}
      ref={ref}
      {...props}
    />
  );
});

Button.displayName = "Button";
