// 04__ai/ai-notes/apps/web/src/components/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		type?: 'button' | 'submit' | 'reset';
		variant?: 'primary' | 'secondary' | 'danger' | 'ghost';
		disabled?: boolean;
		loading?: boolean;
		class?: string;
		onclick?: (e: MouseEvent) => void;
		children?: Snippet;
	}

	let {
		type = 'button',
		variant = 'primary',
		disabled = false,
		loading = false,
		class: customClass = '',
		onclick,
		children,
		...restProps
	}: Props = $props();

	let variantClasses = $derived.by(() => {
		switch (variant) {
			case 'primary':
				return 'bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white shadow-lg shadow-violet-950/20 border border-violet-500/30 hover:border-violet-400/50 hover:shadow-violet-500/20 active:scale-[0.98]';
			case 'secondary':
				return 'bg-slate-100 hover:bg-slate-200 text-slate-800 border border-slate-200 dark:bg-slate-900/60 dark:backdrop-blur-md dark:border-slate-800 dark:text-slate-300 dark:hover:text-white dark:hover:bg-slate-800 active:scale-[0.98]';
			case 'danger':
				return 'bg-red-50 hover:bg-red-100 border border-red-200 text-red-700 dark:bg-red-950/20 dark:hover:bg-red-900/30 dark:border-red-900/30 dark:text-red-400 dark:hover:text-red-300 active:scale-[0.98]';
			case 'ghost':
				return 'text-slate-500 hover:text-slate-800 hover:bg-slate-100 dark:text-slate-400 dark:hover:text-white dark:hover:bg-slate-900/60 active:scale-[0.98]';
			default:
				return '';
		}
	});
</script>

<button
	{type}
	disabled={disabled || loading}
	{onclick}
	class="inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl px-5 py-2.5 text-sm font-medium transition-all duration-300 disabled:pointer-events-none disabled:opacity-50 {variantClasses} {customClass}"
	{...restProps}
>
	{#if loading}
		<span class="h-4 w-4 animate-spin rounded-full border-2 border-current/20 border-t-current"
		></span>
	{/if}
	{#if children}
		{@render children()}
	{/if}
</button>

// 06__full-stack/nimbusdrive/apps/web/src/lib/component/ui/Button.jsx
import React from "react";
import { cn } from "../../utils";

export const Button = React.forwardRef(
  ({ className, variant = "default", size = "default", ...props }, ref) => {
    const baseStyles =
      "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-xl text-sm font-medium transition-all duration-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-teal-500 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 cursor-pointer";

    const variants = {
      default:
        "bg-gradient-to-r from-teal-600 to-emerald-500 text-white shadow-lg shadow-teal-500/20 hover:from-teal-500 hover:to-emerald-400 hover:shadow-teal-500/30",
      destructive: "bg-rose-600 text-white shadow-sm hover:bg-rose-500",
      outline:
        "border border-slate-200 bg-transparent text-slate-700 hover:bg-slate-50 dark:border-slate-800 dark:text-slate-300 dark:hover:bg-slate-900 dark:hover:text-white",
      secondary:
        "bg-slate-100 text-slate-900 hover:bg-slate-250 dark:bg-slate-800 dark:text-slate-100 dark:hover:bg-slate-700",
      ghost:
        "text-slate-600 hover:bg-slate-50 hover:text-slate-900 dark:text-slate-400 dark:hover:bg-slate-900 dark:hover:text-white",
      link: "text-teal-600 dark:text-teal-400 underline-offset-4 hover:underline",
    };

    const sizes = {
      default: "h-10 px-4 py-2",
      sm: "h-9 rounded-lg px-3 text-xs",
      lg: "h-11 rounded-xl px-8",
      icon: "h-10 w-10",
    };

    return (
      <button
        className={cn(baseStyles, variants[variant], sizes[size], className)}
        ref={ref}
        {...props}
      />
    );
  }
);

Button.displayName = "Button";
