// 06__full-stack/barbhq/dashboard/src/components/layout/Sidebar.tsx
import React from "react";
import { Scissors, LogOut } from "lucide-react";
import { SidebarItem } from "./SidebarItem";
import { SidebarGroup } from "./SidebarGroup";
import { navigationConfig } from "../../lib/navigation";
import { useSidebarStore } from "../../store/sidebarStore";
import { useAuth } from "../../features/auth";
import { can } from "../../lib/permissions";
import { cn } from "../../lib/utils";

export interface SidebarProps {
  onItemClick?: () => void;
}

export const Sidebar: React.FC<SidebarProps> = ({ onItemClick }) => {
  const { collapsed } = useSidebarStore();
  const { user, logout } = useAuth();

  const filteredNavigation = navigationConfig.filter((item) => {
    if ("items" in item) {
      const allowedItems = item.items.filter(
        (subItem) => !subItem.permission || can(user, subItem.permission),
      );
      return allowedItems.length > 0;
    }
    return !item.permission || can(user, item.permission);
  });

  return (
    <div className="flex h-full flex-col justify-between py-4 select-none bg-card text-card-foreground">
      <div>
        {/* Brand Logo Header */}
        <div
          className={cn(
            "flex items-center px-4 mb-8",
            collapsed ? "justify-center" : "gap-3",
          )}
        >
          <div className="flex h-9.5 w-9.5 shrink-0 items-center justify-center rounded-lg bg-primary text-primary-foreground shadow-md shadow-primary/10">
            <Scissors className="h-5 w-5 -rotate-45" />
          </div>
          {!collapsed && (
            <div>
              <h1 className="font-serif text-base font-extrabold tracking-wider uppercase text-primary leading-none">
                BarbHQ
              </h1>
              <p className="text-[8px] tracking-[0.2em] uppercase text-muted-foreground mt-0.5 font-bold">
                Shop Console
              </p>
            </div>
          )}
        </div>

        {/* Navigation List */}
        <nav className="flex flex-col gap-1 px-2">
          {filteredNavigation.map((item, idx) => {
            if ("items" in item) {
              const allowedSubItems = item.items.filter(
                (subItem) => !subItem.permission || can(user, subItem.permission),
              );
              return (
                <SidebarGroup
                  key={idx}
                  label={item.label}
                  items={allowedSubItems}
                  collapsed={collapsed}
                  onItemClick={onItemClick}
                />
              );
            }
            return (
              <SidebarItem
                key={item.path}
                label={item.label}
                path={item.path}
                iconName={item.iconName}
                collapsed={collapsed}
                onItemClick={onItemClick}
              />
            );
          })}
        </nav>
      </div>

      {/* Logout Trigger at the bottom */}
      <div className="px-2">
        <button
          onClick={logout}
          className={cn(
            "flex w-full items-center rounded-lg px-3.5 py-3 text-sm font-bold text-destructive hover:bg-destructive/10 transition-all duration-200 gap-3 cursor-pointer outline-hidden focus-visible:ring-2 focus-visible:ring-destructive",
            collapsed ? "justify-center" : "",
          )}
        >
          <LogOut className="h-5 w-5 shrink-0" />
          {!collapsed && <span>Log Out</span>}
        </button>
      </div>
    </div>
  );
};
export default Sidebar;

// 06__full-stack/github-dashboard/src/lib/components/layout/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { navigation } from '$lib/constants/navigation';
	import { Github } from 'lucide-svelte';
	import { cn } from '$lib/utils.js';

	let { class: className } = $props<{ class?: string }>();
</script>

<aside class={cn("flex flex-col h-full bg-card border-r border-border text-card-foreground w-64 select-none", className)}>
	<!-- Brand/Logo Section -->
	<div class="flex items-center gap-3 px-6 py-5 border-b border-border">
		<div class="flex items-center justify-center w-9 h-9 rounded-lg bg-primary text-primary-foreground shadow-md transition-all duration-300 hover:scale-105">
			<Github class="w-5 h-5" />
		</div>
		<div class="flex flex-col">
			<span class="font-bold text-lg tracking-tight leading-none bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text">GitDash</span>
			<span class="text-xs text-muted-foreground mt-0.5 font-medium">GitHub Insights</span>
		</div>
	</div>

	<!-- Navigation Menu Section -->
	<nav class="flex-1 px-4 py-6 space-y-1.5 overflow-y-auto">
		{#each navigation as item}
			{@const isActive = $page.url.pathname === item.href || $page.url.pathname.startsWith(item.href + '/')}
			<a
				href={item.href}
				class={cn(
					"flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-all duration-200 group relative",
					isActive 
						? "bg-secondary text-secondary-foreground font-semibold shadow-sm" 
						: "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
				)}
			>
				{#if isActive}
					<div class="absolute left-0 w-1 h-5 bg-primary rounded-r-md"></div>
				{/if}
				<item.icon class={cn("w-5 h-5 transition-transform duration-200 group-hover:scale-105", isActive ? "text-primary animate-pulse" : "text-muted-foreground group-hover:text-foreground")} />
				<span>{item.title}</span>
			</a>
		{/each}
	</nav>

	<!-- Footer Section -->
	<div class="p-4 border-t border-border bg-muted/20">
		<div class="flex items-center gap-3 px-2 py-2">
			<div class="w-8 h-8 rounded-full bg-gradient-to-tr from-purple-500 to-blue-500 flex items-center justify-center text-white font-bold text-sm shadow-inner">
				G
			</div>
			<div class="flex flex-col overflow-hidden">
				<span class="text-xs font-semibold text-foreground truncate">Guest User</span>
				<span class="text-[10px] text-muted-foreground truncate font-medium">guest@example.com</span>
			</div>
		</div>
	</div>
</aside>
