// 06__full-stack/barbhq/dashboard/src/components/ui/StatCard.tsx
import React from "react";
import { Card, CardContent } from "./card";
import { cn } from "../../lib/utils";
import { ArrowUpRight, ArrowDownRight } from "lucide-react";

export interface StatCardProps {
  title: string;
  value: string | number;
  description?: string;
  icon?: React.ReactNode;
  trend?: {
    value: number;
    isPositive?: boolean;
    label?: string;
  };
  hoverable?: boolean;
  className?: string;
}

export const StatCard: React.FC<StatCardProps> = ({
  title,
  value,
  description,
  icon,
  trend,
  hoverable = true,
  className,
}) => {
  return (
    <Card
      hoverable={hoverable}
      className={cn("overflow-hidden relative", className)}
    >
      <CardContent className="p-6">
        <div className="flex items-center justify-between">
          <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            {title}
          </p>
          {icon && (
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-secondary/80 text-primary shadow-sm">
              {icon}
            </div>
          )}
        </div>
        <div className="mt-2 flex items-baseline gap-2">
          <span className="text-2xl font-bold tracking-tight text-foreground md:text-3xl">
            {value}
          </span>
          {trend && (
            <span
              className={cn(
                "inline-flex items-center gap-0.5 rounded-full px-1.5 py-0.5 text-xs font-semibold",
                trend.isPositive
                  ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                  : "bg-destructive/10 text-destructive",
              )}
            >
              {trend.isPositive ? (
                <ArrowUpRight className="h-3.5 w-3.5" />
              ) : (
                <ArrowDownRight className="h-3.5 w-3.5" />
              )}
              {trend.value}%
            </span>
          )}
        </div>
        {(description || (trend && trend.label)) && (
          <p className="mt-1 text-xs text-muted-foreground font-medium">
            {trend?.label || description}
          </p>
        )}
      </CardContent>
    </Card>
  );
};

// 06__full-stack/brainrot-studio/frontend/src/lib/components/StatCard.svelte
<script lang="ts">
	import { Folder, Bot, Video, Zap, Layers, Sparkles } from 'lucide-svelte';

	let {
		title,
		value,
		subtext,
		icon,
		color = 'purple'
	}: {
		title: string;
		value: number | string;
		subtext?: string;
		icon: 'folder' | 'bot' | 'video' | 'zap' | 'layers' | 'sparkles' | string;
		color?: 'purple' | 'pink' | 'blue' | 'emerald';
	} = $props();

	const colorClasses = {
		purple: 'from-purple-500/20 to-purple-600/5 text-purple-400 border-purple-500/20',
		pink: 'from-pink-500/20 to-pink-600/5 text-pink-400 border-pink-500/20',
		blue: 'from-blue-500/20 to-blue-600/5 text-blue-400 border-blue-500/20',
		emerald: 'from-emerald-500/20 to-emerald-600/5 text-emerald-400 border-emerald-500/20'
	};
</script>

<div class="glass-card glass-card-hover rounded-2xl p-5 border bg-gradient-to-br {colorClasses[color]} relative overflow-hidden group">
	<div class="flex items-center justify-between">
		<div>
			<p class="text-xs font-semibold tracking-wider text-gray-400 uppercase">{title}</p>
			<h3 class="font-heading text-3xl font-extrabold text-white mt-1 group-hover:scale-105 transition-transform duration-300">
				{value}
			</h3>
			{#if subtext}
				<p class="text-xs text-gray-400 mt-1 flex items-center gap-1">
					<span class="inline-block h-1.5 w-1.5 rounded-full bg-current"></span>
					{subtext}
				</p>
			{/if}
		</div>
		<div class="flex h-12 w-12 items-center justify-center rounded-xl bg-white/5 border border-white/10 shadow-inner group-hover:rotate-6 transition-transform duration-300">
			{#if icon === 'folder' || icon === '📁'}
				<Folder class="h-6 w-6 text-emerald-400" />
			{:else if icon === 'bot' || icon === '🤖'}
				<Bot class="h-6 w-6 text-emerald-400" />
			{:else if icon === 'video' || icon === '🎬'}
				<Video class="h-6 w-6 text-blue-400" />
			{:else if icon === 'zap' || icon === '⚡'}
				<Zap class="h-6 w-6 text-pink-400" />
			{:else}
				<Sparkles class="h-6 w-6 text-purple-400" />
			{/if}
		</div>
	</div>
</div>
