// 04__ai/ai-notes/apps/web/src/routes/login/+page.svelte
<script lang="ts">
	import { authClient } from '$lib/auth/client.js';
	import { goto, invalidateAll } from '$app/navigation';
	import GlowBg from '../../components/GlowBg.svelte';
	import Button from '../../components/Button.svelte';
	import Input from '../../components/Input.svelte';

	let email = $state('');
	let password = $state('');
	let loading = $state(false);
	let error = $state('');

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!email || !password) {
			error = 'Please fill in all fields.';
			return;
		}
		error = '';
		loading = true;

		try {
			const { data, error: authError } = await authClient.signIn.email({
				email,
				password,
				callbackURL: '/dashboard'
			});

			if (authError) {
				error = authError.message || 'Failed to sign in. Please check your credentials.';
			} else {
				// Redirect to dashboard
				await goto('/dashboard');
				await invalidateAll();
			}
		} catch (err: any) {
			error = err.message || 'An unexpected error occurred.';
		} finally {
			loading = false;
		}
	}
</script>

<svelte:head>
	<title>Sign In | AI Notes</title>
	<meta name="description" content="Sign in to your AI Notes account." />
</svelte:head>

<div class="relative flex min-h-screen items-center justify-center bg-slate-50 dark:bg-slate-950 px-4 transition-colors duration-300">
	<!-- Background Orbs (only in dark mode) -->
	<div class="hidden dark:block">
		<GlowBg />
	</div>

	<div
		class="relative z-10 w-full max-w-md rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/40 p-8 shadow-xl dark:shadow-2xl backdrop-blur-xl transition-colors duration-350"
	>
		<div class="mb-8 text-center">
			<h1
				class="text-3xl font-extrabold tracking-tight text-slate-800 dark:text-white"
			>
				Welcome Back
			</h1>
			<p class="mt-2 text-sm font-light text-slate-500 dark:text-slate-400">Sign in to access your intelligent space</p>
		</div>

		{#if error}
			<div
				class="mb-6 animate-pulse rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-center text-sm text-red-650 dark:text-red-400"
			>
				{error}
			</div>
		{/if}

		<form onsubmit={handleSubmit} class="space-y-5">
			<Input
				type="email"
				id="email"
				bind:value={email}
				required={true}
				label="Email Address"
				placeholder="you@example.com"
			/>

			<Input
				type="password"
				id="password"
				bind:value={password}
				required={true}
				label="Password"
				placeholder="••••••••"
			/>

			<div class="pt-2">
				<Button type="submit" disabled={loading} {loading} class="w-full py-3">Sign In</Button>
			</div>
		</form>

		<div class="text-slate-500 dark:text-slate-450 mt-8 text-center text-sm">
			Don't have an account yet?
			<a
				href="/register"
				class="font-semibold text-violet-600 dark:text-violet-400 hover:text-violet-700 dark:hover:text-violet-300 transition-colors"
			>
				Create one here
			</a>
		</div>
	</div>
</div>

// 06__full-stack/nimbusdrive/apps/web/src/routes/Login.jsx
import React, { useState, useEffect } from "react";
import { Lock, Loader2, AlertCircle } from "lucide-react";
import { useNavigate, Link } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "../lib/component/ui/Card";
import { Input } from "../lib/component/ui/Input";
import { Button } from "../lib/component/ui/Button";
import { useAuthStore } from "../features/auth/authStore";
import client from "../api/client";

export default function Login() {
  const { user, login } = useAuthStore();
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [errorMsg, setErrorMsg] = useState("");

  // Redirect if already authenticated
  useEffect(() => {
    if (user) {
      navigate({ to: "/dashboard" });
    }
  }, [user, navigate]);

  const loginMutation = useMutation({
    mutationFn: async (credentials) => {
      const response = await client.post("/api/auth/login", credentials);
      return response.data;
    },
    onSuccess: (data) => {
      login(data.token, data.user);
      navigate({ to: "/dashboard" });
    },
    onError: (err) => {
      const serverMessage = err.response?.data?.message || "Failed to log in";
      setErrorMsg(serverMessage);
    },
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    setErrorMsg("");

    if (!email || !password) {
      setErrorMsg("Please fill in all fields");
      return;
    }

    loginMutation.mutate({ email, password });
  };

  return (
    <div className="max-w-md mx-auto py-12">
      <Card className="p-8 border-slate-800/80 bg-slate-950/40 backdrop-blur-md shadow-2xl">
        <CardHeader className="text-center space-y-2 p-0 mb-6">
          <div className="inline-flex bg-teal-500/10 p-3 rounded-xl border border-teal-500/20 mx-auto">
            <Lock className="w-6 h-6 text-teal-400 animate-pulse" />
          </div>
          <CardTitle className="text-2xl font-bold text-white">Welcome Back</CardTitle>
          <CardDescription className="text-slate-400 text-sm">
            Please log in to your account
          </CardDescription>
        </CardHeader>
        <CardContent className="p-0">
          <form onSubmit={handleSubmit} className="space-y-4">
            {errorMsg && (
              <div className="flex items-center gap-2 bg-red-500/10 border border-red-500/20 text-red-400 p-3 rounded-xl text-xs font-medium">
                <AlertCircle className="w-4 h-4 flex-shrink-0" />
                <span>{errorMsg}</span>
              </div>
            )}

            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">
                Email Address
              </label>
              <Input
                type="email"
                placeholder="you@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-teal-500/50 focus:ring-teal-500/20"
                disabled={loginMutation.isPending}
              />
            </div>

            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">
                Password
              </label>
              <Input
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-teal-500/50 focus:ring-teal-500/20"
                disabled={loginMutation.isPending}
              />
            </div>

            <Button
              type="submit"
              className="w-full py-3 font-semibold mt-2 flex justify-center items-center gap-2"
              disabled={loginMutation.isPending}
            >
              {loginMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Logging in...
                </>
              ) : (
                "Log In"
              )}
            </Button>
          </form>

          <p className="text-center text-xs text-slate-500 mt-6">
            Don't have an account?{" "}
            <Link
              to="/register"
              className="text-teal-400 hover:text-teal-300 font-medium transition-colors"
            >
              Sign up
            </Link>
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
