// 06__full-stack/brainrot-studio/frontend/src/routes/register/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { register } from '$lib/api/auth';
	import { toast } from '$lib/state/toast.svelte';
	import Toast from '$lib/components/Toast.svelte';

	let email = $state('');
	let password = $state('');
	let confirmPassword = $state('');
	let error = $state('');
	let loading = $state(false);

	async function submit() {
		error = '';

		if (password !== confirmPassword) {
			error = 'Passwords do not match';
			return;
		}

		loading = true;

		try {
			await register({
				email,
				password
			});

			toast.show('Account created successfully! Please sign in.', 'success');
			await goto('/login');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Registration failed';
			toast.show(error, 'error');
		} finally {
			loading = false;
		}
	}
</script>

<svelte:head>
	<title>Create Account - Brainrot Studio</title>
</svelte:head>

<div class="relative flex min-h-screen items-center justify-center bg-[#08090d] p-6 text-gray-100 selection:bg-emerald-500/30 overflow-hidden">
	<!-- Background Ambient Orbs -->
	<div class="pointer-events-none absolute -top-40 -right-40 h-[600px] w-[600px] rounded-full bg-emerald-600/15 blur-[140px] animate-ambient-1"></div>
	<div class="pointer-events-none absolute -bottom-40 -left-40 h-[600px] w-[600px] rounded-full bg-cyan-600/15 blur-[140px] animate-ambient-2"></div>

	<div class="relative z-10 w-full max-w-md">
		<!-- Brand Banner -->
		<div class="text-center mb-8">
			<div class="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-tr from-emerald-500 to-cyan-500 shadow-xl shadow-emerald-500/30 mb-4 animate-fade-in text-black font-extrabold text-2xl">
				✨
			</div>
			<h1 class="font-heading text-3xl font-extrabold tracking-tight gradient-emerald-cyan">
				Create Account
			</h1>
			<p class="text-xs text-gray-400 mt-1">Join Brainrot Studio to start generating AI short videos</p>
		</div>

		<!-- Register Card -->
		<div class="bg-obsidian-card rounded-3xl p-8 border border-white/10 shadow-2xl backdrop-blur-2xl animate-fade-in">
			{#if error}
				<div class="alert alert-error mb-6 text-xs font-medium rounded-xl">
					<span>{error}</span>
				</div>
			{/if}

			<form
				class="space-y-4"
				onsubmit={(e) => {
					e.preventDefault();
					submit();
				}}
			>
				<div>
					<label for="reg-email" class="block text-xs font-semibold uppercase tracking-wider text-gray-300 mb-2">
						Email Address
					</label>
					<input
						id="reg-email"
						type="email"
						bind:value={email}
						placeholder="name@example.com"
						class="input input-bordered w-full bg-white/5 border-white/10 focus:border-emerald-500 focus:outline-none text-sm text-white placeholder:text-gray-600 rounded-xl"
						required
					/>
				</div>

				<div>
					<label for="reg-password" class="block text-xs font-semibold uppercase tracking-wider text-gray-300 mb-2">
						Password
					</label>
					<input
						id="reg-password"
						type="password"
						bind:value={password}
						placeholder="••••••••"
						class="input input-bordered w-full bg-white/5 border-white/10 focus:border-emerald-500 focus:outline-none text-sm text-white placeholder:text-gray-600 rounded-xl"
						required
					/>
				</div>

				<div>
					<label for="reg-confirm-password" class="block text-xs font-semibold uppercase tracking-wider text-gray-300 mb-2">
						Confirm Password
					</label>
					<input
						id="reg-confirm-password"
						type="password"
						bind:value={confirmPassword}
						placeholder="••••••••"
						class="input input-bordered w-full bg-white/5 border-white/10 focus:border-emerald-500 focus:outline-none text-sm text-white placeholder:text-gray-600 rounded-xl"
						required
					/>
				</div>

				<button
					type="submit"
					class="btn-emerald w-full py-3 text-sm font-semibold rounded-xl mt-2"
					disabled={loading}
				>
					{loading ? 'Creating Account...' : 'Register'}
				</button>
			</form>

			<div class="mt-6 text-center text-xs text-gray-400 border-t border-white/10 pt-4">
				Already have an account?
				<a href="/login" class="font-semibold text-emerald-400 hover:text-emerald-300 ml-1">
					Sign In
				</a>
			</div>
		</div>
	</div>
</div>

<Toast />
```...

// 06__full-stack/nimbusdrive/apps/web/src/routes/Register.jsx
import React, { useState, useEffect } from "react";
import { UserPlus, Loader2, AlertCircle } from "lucide-react";
import { useNavigate, Link } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../lib/component/ui/Card";
import { Input } from "../lib/component/ui/Input";
import { Button } from "../lib/component/ui/Button";
import { useAuthStore } from "../features/auth/authStore";
import client from "../api/client";

export default function Register() {
  const { user, login } = useAuthStore();
  const navigate = useNavigate();
  
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [errorMsg, setErrorMsg] = useState("");

  // Redirect if already authenticated
  useEffect(() => {
    if (user) {
      navigate({ to: "/" });
    }
  }, [user, navigate]);

  const registerMutation = useMutation({
    mutationFn: async (formData) => {
      const response = await client.post("/api/auth/register", formData);
      return response.data;
    },
    onSuccess: (data) => {
      login(data.token, data.user);
      navigate({ to: "/" });
    },
    onError: (err) => {
      // Decode backend errors
      const data = err.response?.data;
      if (data?.errors && data.errors.length > 0) {
        setErrorMsg(`${data.errors[0].field}: ${data.errors[0].message}`);
      } else {
        setErrorMsg(data?.message || "Failed to create account");
      }
    },
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    setErrorMsg("");

    if (!name || !email || !password || !confirmPassword) {
      setErrorMsg("All fields are required");
      return;
    }

    if (password.length < 8) {
      setErrorMsg("Password must be at least 8 characters long");
      return;
    }

    if (password !== confirmPassword) {
      setErrorMsg("Passwords do not match");
      return;
    }

    registerMutation.mutate({ name, email, password, confirmPassword });
  };

  return (
    <div className="max-w-md mx-auto py-12">
      <Card className="p-8 border-slate-800/80 bg-slate-950/40 backdrop-blur-md shadow-2xl">
        <CardHeader className="text-center space-y-2 p-0 mb-6">
          <div className="inline-flex bg-indigo-500/10 p-3 rounded-xl border border-indigo-500/20 mx-auto">
            <UserPlus className="w-6 h-6 text-indigo-400 animate-pulse" />
          </div>
          <CardTitle className="text-2xl font-bold text-white">Create Account</CardTitle>
          <CardDescription className="text-slate-400 text-sm">Join Nimbus Drive storage cluster</CardDescription>
        </CardHeader>
        <CardContent className="p-0">
          <form onSubmit={handleSubmit} className="space-y-4">
            {errorMsg && (
              <div className="flex items-center gap-2 bg-red-500/10 border border-red-500/20 text-red-400 p-3 rounded-xl text-xs font-medium">
                <AlertCircle className="w-4 h-4 flex-shrink-0" />
                <span>{errorMsg}</span>
              </div>
            )}
            
            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">Full Name</label>
              <Input
                type="text"
                placeholder="John Doe"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-indigo-500/50 focus:ring-indigo-500/20"
                disabled={registerMutation.isPending}
              />
            </div>

            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">Email Address</label>
              <Input
                type="email"
                placeholder="you@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-indigo-500/50 focus:ring-indigo-500/20"
                disabled={registerMutation.isPending}
              />
            </div>

            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">Password</label>
              <Input
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-indigo-500/50 focus:ring-indigo-500/20"
                disabled={registerMutation.isPending}
              />
            </div>

            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">Confirm Password</label>
              <Input
                type="password"
                placeholder="••••••••"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-indigo-500/50 focus:ring-indigo-500/20"
                disabled={registerMutation.isPending}
              />
            </div>

            <Button 
              type="submit" 
              className="w-full py-3 font-semibold mt-2 flex justify-center items-center gap-2"
              disabled={registerMutation.isPending}
            >
              {registerMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Creating account...
                </>
              ) : (
                "Register"
              )}
            </Button>
          </form>

          <p className="text-center text-xs text-slate-500 mt-6">
            Already have an account?{" "}
            <Link to="/login" className="text-indigo-400 hover:text-indigo-300 font-medium transition-colors">
              Log in
            </Link>
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
