// 06__full-stack/simpler/apps/frontend/src/routes/register/+page.svelte
<script lang="ts">
	import { auth } from '$lib/stores/auth.svelte';
	import { goto } from '$app/navigation';

	let email = $state('');
	let password = $state('');
	let confirmPassword = $state('');
	let error = $state('');
	let loading = $state(false);

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		error = '';

		if (password !== confirmPassword) {
			error = 'Passwords do not match';
			return;
		}

		if (password.length < 8) {
			error = 'Password must be at least 8 characters long';
			return;
		}

		loading = true;

		try {
			await auth.register(email, password);
			goto('/dashboard');
		} catch (err: any) {
			error = err.message || 'Failed to create account';
		} finally {
			loading = false;
		}
	}
</script>

<div
	class="w-full max-w-md rounded-2xl border border-slate-700/50 bg-slate-800/60 p-8 shadow-2xl backdrop-blur-md"
>
	<div class="mb-8 text-center">
		<h1 class="text-3xl font-bold tracking-tight text-white">Create an account</h1>
		<p class="mt-2 text-sm text-slate-400">Get started with TaskNotes today</p>
	</div>

	{#if error}
		<div
			class="mb-6 flex items-center gap-2 rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-400"
		>
			<svg class="h-5 w-5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="2"
					d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
				/>
			</svg>
			<span>{error}</span>
		</div>
	{/if}

	<form onsubmit={handleSubmit} class="space-y-4">
		<div>
			<label for="email" class="mb-1.5 block text-sm font-medium text-slate-300"
				>Email address</label
			>
			<input
				id="email"
				type="email"
				bind:value={email}
				required
				placeholder="you@example.com"
				class="w-full rounded-xl border border-slate-700/80 bg-slate-900/60 px-4 py-2.5 text-sm text-white placeholder-slate-500 transition-all focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/50 focus:outline-none"
			/>
		</div>

		<div>
			<label for="password" class="mb-1.5 block text-sm font-medium text-slate-300">Password</label>
			<input
				id="password"
				type="password"
				bind:value={password}
				required
				placeholder="At least 8 characters"
				class="w-full rounded-xl border border-slate-700/80 bg-slate-900/60 px-4 py-2.5 text-sm text-white placeholder-slate-500 transition-all focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/50 focus:outline-none"
			/>
		</div>

		<div>
			<label for="confirmPassword" class="mb-1.5 block text-sm font-medium text-slate-300"
				>Confirm Password</label
			>
			<input
				id="confirmPassword"
				type="password"
				bind:value={confirmPassword}
				required
				placeholder="••••••••"
				class="w-full rounded-xl border border-slate-700/80 bg-slate-900/60 px-4 py-2.5 text-sm text-white placeholder-slate-500 transition-all focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/50 focus:outline-none"
			/>
		</div>

		<button
			type="submit"
			disabled={loading}
			class="mt-2 w-full rounded-xl bg-indigo-600 px-4 py-3 text-sm font-medium text-white shadow-lg shadow-indigo-600/20 transition-all duration-150 hover:bg-indigo-500 focus:ring-2 focus:ring-indigo-500/50 focus:outline-none active:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50"
		>
			{loading ? 'Creating account...' : 'Register'}
		</button>
	</form>

	<p class="mt-8 text-center text-sm text-slate-400">
		Already have an account?
		<a
			href="/login"
			class="font-medium text-indigo-400 underline underline-offset-4 transition-colors hover:text-indigo-300"
			>Sign In</a
		>
	</p>
</div>

// 06__full-stack/nimbusdrive/apps/web/src/routes/Register.jsx
import React, { useState, useEffect } from "react";
import { UserPlus, Loader2, AlertCircle } from "lucide-react";
import { useNavigate, Link } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../lib/component/ui/Card";
import { Input } from "../lib/component/ui/Input";
import { Button } from "../lib/component/ui/Button";
import { useAuthStore } from "../features/auth/authStore";
import client from "../api/client";

export default function Register() {
  const { user, login } = useAuthStore();
  const navigate = useNavigate();
  
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [errorMsg, setErrorMsg] = useState("");

  // Redirect if already authenticated
  useEffect(() => {
    if (user) {
      navigate({ to: "/" });
    }
  }, [user, navigate]);

  const registerMutation = useMutation({
    mutationFn: async (formData) => {
      const response = await client.post("/api/auth/register", formData);
      return response.data;
    },
    onSuccess: (data) => {
      login(data.token, data.user);
      navigate({ to: "/" });
    },
    onError: (err) => {
      // Decode backend errors
      const data = err.response?.data;
      if (data?.errors && data.errors.length > 0) {
        setErrorMsg(`${data.errors[0].field}: ${data.errors[0].message}`);
      } else {
        setErrorMsg(data?.message || "Failed to create account");
      }
    },
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    setErrorMsg("");

    if (!name || !email || !password || !confirmPassword) {
      setErrorMsg("All fields are required");
      return;
    }

    if (password.length < 8) {
      setErrorMsg("Password must be at least 8 characters long");
      return;
    }

    if (password !== confirmPassword) {
      setErrorMsg("Passwords do not match");
      return;
    }

    registerMutation.mutate({ name, email, password, confirmPassword });
  };

  return (
    <div className="max-w-md mx-auto py-12">
      <Card className="p-8 border-slate-800/80 bg-slate-950/40 backdrop-blur-md shadow-2xl">
        <CardHeader className="text-center space-y-2 p-0 mb-6">
          <div className="inline-flex bg-indigo-500/10 p-3 rounded-xl border border-indigo-500/20 mx-auto">
            <UserPlus className="w-6 h-6 text-indigo-400 animate-pulse" />
          </div>
          <CardTitle className="text-2xl font-bold text-white">Create Account</CardTitle>
          <CardDescription className="text-slate-400 text-sm">Join Nimbus Drive storage cluster</CardDescription>
        </CardHeader>
        <CardContent className="p-0">
          <form onSubmit={handleSubmit} className="space-y-4">
            {errorMsg && (
              <div className="flex items-center gap-2 bg-red-500/10 border border-red-500/20 text-red-400 p-3 rounded-xl text-xs font-medium">
                <AlertCircle className="w-4 h-4 flex-shrink-0" />
                <span>{errorMsg}</span>
              </div>
            )}
            
            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">Full Name</label>
              <Input
                type="text"
                placeholder="John Doe"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-indigo-500/50 focus:ring-indigo-500/20"
                disabled={registerMutation.isPending}
              />
            </div>

            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">Email Address</label>
              <Input
                type="email"
                placeholder="you@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-indigo-500/50 focus:ring-indigo-500/20"
                disabled={registerMutation.isPending}
              />
            </div>

            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">Password</label>
              <Input
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-indigo-500/50 focus:ring-indigo-500/20"
                disabled={registerMutation.isPending}
              />
            </div>

            <div className="space-y-2">
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider">Confirm Password</label>
              <Input
                type="password"
                placeholder="••••••••"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                className="bg-slate-900/50 border-slate-800 text-slate-100 placeholder-slate-500 focus:border-indigo-500/50 focus:ring-indigo-500/20"
                disabled={registerMutation.isPending}
              />
            </div>

            <Button 
              type="submit" 
              className="w-full py-3 font-semibold mt-2 flex justify-center items-center gap-2"
              disabled={registerMutation.isPending}
            >
              {registerMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Creating account...
                </>
              ) : (
                "Register"
              )}
            </Button>
          </form>

          <p className="text-center text-xs text-slate-500 mt-6">
            Already have an account?{" "}
            <Link to="/login" className="text-indigo-400 hover:text-indigo-300 font-medium transition-colors">
              Log in
            </Link>
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
