// 06__full-stack/github-dashboard/src/lib/components/layout/AppLayout.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import Sidebar from './Sidebar.svelte';
	import Navbar from './Navbar.svelte';
	import * as Sheet from '$lib/components/ui/sheet/index.js';

	let { children } = $props<{ children: Snippet }>();
	let isMobileMenuOpen = $state(false);
</script>

<div class="min-h-screen bg-background text-foreground flex flex-col">
	<!-- Desktop Sidebar (Hidden on mobile) -->
	<Sidebar class="fixed inset-y-0 left-0 z-30 hidden lg:flex" />

	<!-- Mobile Sidebar Drawer -->
	<Sheet.Root bind:open={isMobileMenuOpen}>
		<Sheet.Content side="left" class="p-0 w-64 border-r-0">
			<Sidebar class="h-full border-r-0" />
		</Sheet.Content>
	</Sheet.Root>

	<!-- Main Content Wrapper (shifted left on desktop to accommodate Sidebar) -->
	<div class="flex-1 flex flex-col lg:pl-64 min-w-0 transition-all duration-300">
		<Navbar onMenuClick={() => (isMobileMenuOpen = true)} />
		
		<main class="flex-1 p-6 md:p-8 max-w-7xl w-full mx-auto animate-fade-in">
			{@render children()}
		</main>
	</div>
</div>

<style>
	:global(.animate-fade-in) {
		animation: fadeIn 0.3s ease-out-in forwards;
	}

	@keyframes fadeIn {
		from {
			opacity: 0;
			transform: translateY(4px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}
</style>

// 06__full-stack/barbhq/web/src/components/layout/AppLayout.tsx
import React from "react";
import { Sidebar } from "./Sidebar";
import { TopNavbar } from "./TopNavbar";
import { Footer } from "./Footer";
import { Drawer } from "../ui/drawer";
import { useSidebarStore } from "../../store/sidebarStore";
import { cn } from "../../lib/utils";

interface AppLayoutProps {
  children: React.ReactNode;
}

export const AppLayout: React.FC<AppLayoutProps> = ({ children }) => {
  const { collapsed, mobileOpen, setMobileOpen } = useSidebarStore();

  return (
    <div className="flex h-screen w-full bg-background overflow-hidden font-sans">
      {/* 1. Desktop Sidebar */}
      <aside
        className={cn(
          "hidden md:flex flex-col h-full bg-card border-r border-border transition-all duration-300 z-20 shrink-0",
          collapsed ? "w-20" : "w-64",
        )}
      >
        <Sidebar />
      </aside>

      {/* 2. Mobile Sidebar Drawer */}
      <Drawer
        isOpen={mobileOpen}
        onClose={() => setMobileOpen(false)}
        position="left"
        title="BarbHQ Navigation"
        className="max-w-[280px]"
      >
        <div className="h-full -mx-6 -mt-5">
          <Sidebar onItemClick={() => setMobileOpen(false)} />
        </div>
      </Drawer>

      {/* 3. Main content body */}
      <div className="flex flex-1 flex-col overflow-hidden">
        {/* Top Navbar Header */}
        <TopNavbar onMenuToggle={() => setMobileOpen(true)} />

        {/* Content Viewer Body */}
        <main className="flex-1 overflow-y-auto bg-background/35 flex flex-col justify-between">
          <div className="flex-1">{children}</div>
          <Footer />
        </main>
      </div>
    </div>
  );
};
export default AppLayout;
