// 06__full-stack/nimbusdrive/apps/web/src/lib/component/ui/Input.jsx
import React from "react";
import { cn } from "../../utils";

export const Input = React.forwardRef(({ className, type = "text", ...props }, ref) => {
  return (
    <input
      type={type}
      className={cn(
        "flex h-11 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-800 placeholder-slate-400 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300 dark:placeholder-slate-600 focus:outline-none focus:border-teal-500 focus:ring-1 focus:ring-teal-500 disabled:cursor-not-allowed disabled:opacity-50 transition-all duration-200",
        className
      )}
      ref={ref}
      {...props}
    />
  );
});

Input.displayName = "Input";

// 04__ai/ai-notes/apps/web/src/components/Input.svelte
<script lang="ts">
	interface Props {
		value?: string;
		label?: string;
		type?: string;
		id: string;
		required?: boolean;
		placeholder?: string;
		error?: string;
		class?: string;
	}

	let {
		value = $bindable(''),
		label,
		type = 'text',
		id,
		required = false,
		placeholder = '',
		error = '',
		class: customClass = '',
		...restProps
	}: Props = $props();
</script>

<div class="flex w-full flex-col items-start space-y-2 {customClass}">
	{#if label}
		<label for={id} class="block text-xs font-semibold tracking-wider text-slate-400 uppercase">
			{label}
		</label>
	{/if}

	<div class="relative w-full">
		<input
			{type}
			{id}
			bind:value
			{required}
			{placeholder}
			class="w-full rounded-xl px-4 py-3 text-sm outline-none transition-all duration-200 bg-slate-50 border border-slate-200 text-slate-800 placeholder:text-slate-400 focus:bg-white focus:border-violet-600 dark:bg-slate-900 dark:border-slate-800 dark:text-white dark:placeholder:text-slate-600 dark:focus:bg-slate-950 dark:focus:border-violet-500 focus:outline-none"
			class:border-red-500={error}
			class:focus:border-red-500={error}
			class:focus:ring-red-500={error}
			{...restProps}
		/>
	</div>

	{#if error}
		<p class="animate-pulse text-xs font-medium text-red-400">
			{error}
		</p>
	{/if}
</div>
