// 04__ai/ai-notes/apps/web/src/components/Input.svelte
<script lang="ts">
	interface Props {
		value?: string;
		label?: string;
		type?: string;
		id: string;
		required?: boolean;
		placeholder?: string;
		error?: string;
		class?: string;
	}

	let {
		value = $bindable(''),
		label,
		type = 'text',
		id,
		required = false,
		placeholder = '',
		error = '',
		class: customClass = '',
		...restProps
	}: Props = $props();
</script>

<div class="flex w-full flex-col items-start space-y-2 {customClass}">
	{#if label}
		<label for={id} class="block text-xs font-semibold tracking-wider text-slate-400 uppercase">
			{label}
		</label>
	{/if}

	<div class="relative w-full">
		<input
			{type}
			{id}
			bind:value
			{required}
			{placeholder}
			class="w-full rounded-xl px-4 py-3 text-sm outline-none transition-all duration-200 bg-slate-50 border border-slate-200 text-slate-800 placeholder:text-slate-400 focus:bg-white focus:border-violet-600 dark:bg-slate-900 dark:border-slate-800 dark:text-white dark:placeholder:text-slate-600 dark:focus:bg-slate-950 dark:focus:border-violet-500 focus:outline-none"
			class:border-red-500={error}
			class:focus:border-red-500={error}
			class:focus:ring-red-500={error}
			{...restProps}
		/>
	</div>

	{#if error}
		<p class="animate-pulse text-xs font-medium text-red-400">
			{error}
		</p>
	{/if}
</div>

// 06__full-stack/barbhq/web/src/components/ui/input.tsx
import React from "react";
import { cn } from "../../lib/utils";

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
  helperText?: string;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
}

export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  (
    {
      className,
      type = "text",
      label,
      error,
      helperText,
      leftIcon,
      rightIcon,
      id,
      "aria-describedby": ariaDescribedby,
      ...props
    },
    ref,
  ) => {
    const generatedId = React.useId();
    const inputId = id ?? generatedId;
    const describedBy = [
      ariaDescribedby,
      error ? `${inputId}-error` : helperText ? `${inputId}-helper` : undefined,
    ]
      .filter(Boolean)
      .join(" ") || undefined;

    return (
      <div className="flex flex-col gap-1.5 w-full">
        {label && (
          <label
            htmlFor={inputId}
            className="font-semibold text-muted-foreground text-xs uppercase tracking-wider"
          >
            {label}
          </label>
        )}
        <div className="relative flex items-center">
          {leftIcon && (
            <div className="left-3.5 absolute flex justify-center items-center text-muted-foreground pointer-events-none">
              {leftIcon}
            </div>
          )}
          <input
            id={inputId}
            type={type}
            ref={ref}
            aria-invalid={error ? true : undefined}
            aria-describedby={describedBy}
            className={cn(
              "bg-card disabled:opacity-50 px-3.5 py-2.5 border border-border focus:border-primary rounded-lg focus:outline-none focus:ring-1 focus:ring-primary w-full placeholder:text-muted-foreground text-sm transition-all duration-200 disabled:cursor-not-allowed",
              {
                "pl-10": leftIcon,
                "pr-10": rightIcon,
                "border-destructive focus:border-destructive focus:ring-destructive":
                  error,
              },
              className,
            )}
            {...props}
          />
          {rightIcon && (
            <div className="right-3.5 absolute flex justify-center items-center text-muted-foreground">
              {rightIcon}
            </div>
          )}
        </div>
        {error ? (
          <span
            id={`${inputId}-error`}
            className="font-medium text-destructive text-xs animate-fade-in"
          >
            {error}
          </span>
        ) : helperText ? (
          <span id={`${inputId}-helper`} className="text-muted-foreground text-xs">
            {helperText}
          </span>
        ) : null}
      </div>
    );
  },
);

Input.displayName = "Input";
