// 06__full-stack/serverpilot/apps/web/src/lib/components/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import Spinner from './Spinner.svelte';

	let {
		children,
		variant = 'default',
		size = 'md',
		type = 'button',
		disabled = false,
		loading = false,
		onclick,
		class: className = '',
		...rest
	} = $props<{
		children: Snippet;
		variant?: 'default' | 'secondary' | 'outline' | 'ghost' | 'destructive';
		size?: 'sm' | 'md' | 'lg';
		type?: 'button' | 'submit' | 'reset';
		disabled?: boolean;
		loading?: boolean;
		onclick?: (e: MouseEvent) => void;
		class?: string;
		[key: string]: any;
	}>();

	const variantClasses = {
		default:
			'bg-indigo-600 text-white hover:bg-indigo-500 shadow-lg shadow-indigo-500/10 focus-visible:ring-indigo-500 active:scale-[0.98]',
		secondary:
			'bg-zinc-800 text-zinc-150 hover:bg-zinc-700 border border-zinc-700/60 focus-visible:ring-zinc-700 active:scale-[0.98]',
		outline:
			'bg-transparent text-zinc-300 border border-zinc-700 hover:bg-zinc-900/50 hover:text-zinc-100 focus-visible:ring-zinc-700 active:scale-[0.98]',
		ghost:
			'bg-transparent text-zinc-400 hover:bg-zinc-900/50 hover:text-zinc-200 focus-visible:ring-zinc-800',
		destructive:
			'bg-red-950/40 text-red-200 border border-red-900/50 hover:bg-red-900/40 hover:text-red-100 focus-visible:ring-red-700 active:scale-[0.98]'
	};

	const sizeClasses = {
		sm: 'h-9 px-3 text-xs rounded-md',
		md: 'h-10 px-4 py-2 text-sm rounded-lg',
		lg: 'h-11 px-8 text-base rounded-xl'
	};
</script>

<button
	{type}
	disabled={disabled || loading}
	{onclick}
	class="inline-flex cursor-pointer items-center justify-center gap-2 font-semibold transition-all select-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-zinc-950 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 {variantClasses[
		variant
	]} {sizeClasses[size]} {className}"
	{...rest}
>
	{#if loading}
		<Spinner size="sm" color={variant === 'default' ? 'white' : 'indigo'} />
	{/if}
	{@render children()}
</button>

// 06__full-stack/shop-stack/src/components/ui/button.tsx
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import type * as React from "react";

import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 cursor-pointer whitespace-nowrap rounded-md text-sm font-mono font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive text-white hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
        outline:
          "border-2 bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50",
        secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost:
          "border-2 border-dashed text-body-70 hover:border-transparent hover:bg-accent hover:text-accent-foreground dark:hover:bg-primary",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2 has-[>svg]:px-3",
        sm: "h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5",
        lg: "min-h-12 @7xl:h-16 py-3 text-base @7xl:text-lg rounded-xl px-8",
        icon: "size-9",
        "icon-sm": "size-8",
        "icon-lg":
          "w-12 @7xl:w-16 h-12 @7xl:h-16 text-base @7xl:text-lg rounded-xl px-0 text-secondary-foreground [&_svg:not([class*='size-'])]:size-auto hover:bg-primary",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

function Button({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean;
  }) {
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  );
}

export { Button, buttonVariants };
